DROP TABLE IF EXISTS leave;
DROP TABLE IF EXISTS contract;
DROP TABLE IF EXISTS  employee;
DROP TABLE IF EXISTS token;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS role;
DROP EXTENSION IF EXISTS citext;
DROP EXTENSION IF EXISTS "uuid-ossp";



