// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: lichess.sql

package db

import (
	"context"
)

const getLichessTeamMembers = `-- name: GetLichessTeamMembers :many
SELECT lichess_id from lichess
`

func (q *Queries) GetLichessTeamMembers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getLichessTeamMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var lichess_id string
		if err := rows.Scan(&lichess_id); err != nil {
			return nil, err
		}
		items = append(items, lichess_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
