// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: lichess.sql

package db

import (
	"context"
)

const getLichessTeamMembers = `-- name: GetLichessTeamMembers :many
SELECT id, lichess_id, username, created_at from lichess
`

func (q *Queries) GetLichessTeamMembers(ctx context.Context) ([]Lichess, error) {
	rows, err := q.db.QueryContext(ctx, getLichessTeamMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lichess{}
	for rows.Next() {
		var i Lichess
		if err := rows.Scan(
			&i.ID,
			&i.LichessID,
			&i.Username,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
