// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Lichess struct {
	ID        int32     `json:"id"`
	LichessID string    `json:"lichess_id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}

type Token struct {
	Hash   []byte    `json:"hash"`
	UserID uuid.UUID `json:"user_id"`
	Expiry time.Time `json:"expiry"`
	Scope  string    `json:"scope"`
}

type User struct {
	ID               uuid.UUID `json:"id"`
	Username         string    `json:"username"`
	FullName         string    `json:"full_name"`
	LichessUsername  string    `json:"lichess_username"`
	ChesscomUsername string    `json:"chesscom_username"`
	PhoneNumber      string    `json:"phone_number"`
	PasswordHash     []byte    `json:"password_hash"`
	Passcode         []byte    `json:"passcode"`
	Activated        bool      `json:"activated"`
	Enabled          bool      `json:"enabled"`
	Photo            string    `json:"photo"`
	CreatedAt        time.Time `json:"created_at"`
}
